/**
 * Bundles the script that exported pages run, `src/export/runtime`, with its
 * stylesheet and the strings of every locale, into `dist/runtime.ts`.
 * `renderHtmlDocument` inlines both into each page, so the hosts need no
 * bundler of their own to export a deck. Run after `pnpm i18n:make-json`,
 * which compiles the strings.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'vite';

const packageRoot = fileURLToPath( new URL( '..', import.meta.url ) );
const outFile = resolve( packageRoot, 'dist/runtime.ts' );

// Resolved from this package, since the WordPress packages that import React
// do not depend on Preact.
const preactRoot = dirname(
	createRequire( import.meta.url ).resolve( 'preact/package.json' )
);
const preact = ( path ) => resolve( preactRoot, path );

const [ { output } ] = await build( {
	configFile: false,
	root: packageRoot,
	logLevel: 'warn',
	// Renders the toolbar with Preact, which is far smaller than React, in
	// place of React for `@wordpress/element` and the JSX.
	resolve: {
		alias: [
			{
				find: /^react$/,
				replacement: preact( 'compat/dist/compat.mjs' ),
			},
			{
				find: /^react-dom$/,
				replacement: preact( 'compat/dist/compat.mjs' ),
			},
			{
				find: /^react-dom\/client$/,
				replacement: preact( 'compat/client.mjs' ),
			},
			{
				find: /^react\/jsx-runtime$/,
				replacement: preact( 'jsx-runtime/dist/jsxRuntime.mjs' ),
			},
		],
	},
	// Library mode leaves `process.env.NODE_ENV` as it is, which
	// `@wordpress/hooks` reads, and which a page does not define.
	define: { 'process.env.NODE_ENV': JSON.stringify( 'production' ) },
	build: {
		write: false,
		lib: {
			entry: resolve( packageRoot, 'src/export/runtime/index.ts' ),
			formats: [ 'iife' ],
			name: 'markBricksExport',
		},
	},
} );

const script = output.find( ( file ) => file.type === 'chunk' ).code.trim();
const style = output
	.filter( ( file ) => file.fileName.endsWith( '.css' ) )
	.map( ( file ) => String( file.source ).trim() )
	.join( '' );

// Keeps the code from closing the `<script>` and `<style>` elements early.
const inline = ( code, tag ) =>
	code.replace( new RegExp( `</(${ tag })`, 'gi' ), '<\\/$1' );

await mkdir( resolve( packageRoot, 'dist' ), { recursive: true } );
await writeFile(
	outFile,
	[
		'// Generated by `pnpm build` from `src/export/runtime`. Do not edit.',
		`export const runtimeScript = ${ JSON.stringify(
			inline( script, 'script' )
		) };`,
		`export const runtimeStyle = ${ JSON.stringify(
			inline( style, 'style' )
		) };`,
		'',
	].join( '\n' )
);

console.log( `Wrote ${ outFile }` );
